exports.scriptureData = [
  {
    id: 1,
    name: "Rigveda",
    description:
      "The oldest of the Vedas, containing hymns to be recited by the hotar.",
    chapters: 10,
    thumbnail: "",
    category: "Vedas",
  },
  {
    id: 2,
    name: "Samaveda",
    description: "The Veda of melodies and chants.",
    chapters: 75,
    thumbnail: "",
    category: "Vedas",
  },
  {
    id: 3,
    name: "Yajurveda",
    description: "The Veda of ritual formulas.",
    chapters: 40,
    thumbnail: "",
    category: "Vedas",
  },
  {
    id: 4,
    name: "Atharvaveda",
    description: "The Veda of magical formulas.",
    chapters: 20,
    thumbnail: "",
    category: "Vedas",
  },
  {
    id: 5,
    name: "Isha Upanishad",
    description:
      "One of the shortest Upanishads, discussing the nature of reality.",
    chapters: 1,
    thumbnail: "",
    category: "Upanishads",
  },
  {
    id: 6,
    name: "Kena Upanishad",
    description: "Explores the nature of knowledge and the self.",
    chapters: 4,
    thumbnail: "",
    category: "Upanishads",
  },
  {
    id: 7,
    name: "Katha Upanishad",
    description:
      "A dialogue between Nachiketa and Yama, discussing life and death.",
    chapters: 2,
    thumbnail: "",
    category: "Upanishads",
  },
  {
    id: 8,
    name: "Mandukya Upanishad",
    description: "Focuses on the syllable Aum and its philosophical meaning.",
    chapters: 1,
    thumbnail: "",
    category: "Upanishads",
  },
  {
    id: 9,
    name: "Bhagavata Purana",
    description: "A key text in the Bhakti tradition.",
    chapters: 12,
    thumbnail: "",
    category: "Puranas",
  },
  {
    id: 10,
    name: "Vishnu Purana",
    description:
      "One of the eighteen Mahapuranas, it is a key text for Vaishnavism.",
    chapters: 6,
    thumbnail: "",
    category: "Puranas",
  },
  {
    id: 11,
    name: "Shiva Purana",
    description: "One of the eighteen Mahapuranas, it is dedicated to Shiva.",
    chapters: 7,
    thumbnail: "",
    category: "Puranas",
  },
  {
    id: 12,
    name: "Padma Purana",
    description:
      "One of the eighteen Mahapuranas, it discusses religion and art.",
    chapters: 5,
    thumbnail: "",
    category: "Puranas",
  },
  {
    id: 13,
    name: "Valmiki Ramayana",
    description: "The original epic written by Sage Valmiki.",
    chapters: 7,
    thumbnail: "",
    category: "Ramayana",
  },
  {
    id: 14,
    name: "Ramcharitmanas",
    description: "A retelling of the Ramayana in Awadhi by Tulsidas.",
    chapters: 7,
    thumbnail: "",
    category: "Ramayana",
  },
  {
    id: 15,
    name: "Mahabharata",
    description:
      "The epic narrative of the Kurukshetra war and the fates of the Kaurava and the Pandava princes.",
    chapters: 18,
    thumbnail: "",
    category: "Mahabharata",
  },
  {
    id: 16,
    name: "Bhagavad Gita",
    description:
      "A 700-verse Hindu scripture that is part of the Mahabharata, a conversation between prince Arjuna and the god Krishna.",
    chapters: 18,
    thumbnail: "",
    category: "Mahabharata",
  },
  {
    id: 17,
    name: "Brahma Purana",
    description: "One of the eighteen Mahapuranas, named after Brahma.",
    chapters: 246,
    thumbnail: "",
    category: "Puranas",
  },
  {
    id: 18,
    name: "Markandeya Purana",
    description:
      "One of the eighteen Mahapuranas, containing the Devi Mahatmya.",
    chapters: 137,
    thumbnail: "",
    category: "Puranas",
  },
  {
    id: 19,
    name: "Garuda Purana",
    description:
      "One of the eighteen Mahapuranas, contains details of heaven and hell.",
    chapters: 248,
    thumbnail: "",
    category: "Puranas",
  },
  {
    id: 20,
    name: "Narayana Upanishad",
    description: "Discusses the Supreme Being Narayana.",
    chapters: 1,
    thumbnail: "",
    category: "Upanishads",
  },
];
